### ISSUE TITLE
RuntimeValue substitution

### ISSUE THREAD

**Issue by jhl667** [galaxyproject/bioblend#158]
Trying to substitute {"**class**": "RuntimeValue"} values while setting parameters.  This returns referenced  Galaxy error.  Setting these as dummy values instead of runtime values allows the workflow to run as expected.

Running command:
gi.workflows.run_workflow(workflow_id, datamap, params=param_set, history_name=hist_name, import_inputs_to_history=True)

```
galaxy.web.framework.decorators ERROR 2015-08-24 20:20:27,397 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/home/groups/clinical/Galaxy/galaxy-dist/lib/galaxy/web/framework/decorators.py", line 251, in decorator
    rval = func( self, trans, *args, **kwargs)
  File "/home/groups/clinical/Galaxy/galaxy-dist/lib/galaxy/webapps/galaxy/api/workflows.py", line 199, in create
    populate_state=True,
  File "/home/groups/clinical/Galaxy/galaxy-dist/lib/galaxy/workflow/run.py", line 22, in invoke
    return __invoke( trans, workflow, workflow_run_config, workflow_invocation, populate_state )
  File "/home/groups/clinical/Galaxy/galaxy-dist/lib/galaxy/workflow/run.py", line 61, in __invoke
    modules.populate_module_and_state( trans, workflow, workflow_run_config.param_map )
  File "/home/groups/clinical/Galaxy/galaxy-dist/lib/galaxy/workflow/modules.py", line 1068, in populate_module_and_stat
    step_errors = module_injector.inject( step, step_args=step_args, source="json" )
  File "/home/groups/clinical/Galaxy/galaxy-dist/lib/galaxy/workflow/modules.py", line 1049, in inject
    step.upgrade_messages = module.check_and_update_state()
  File "/home/groups/clinical/Galaxy/galaxy-dist/lib/galaxy/workflow/modules.py", line 743, in check_and_update_state
    return self.tool.check_and_update_param_values( inputs, self.trans, allow_workflow_parameters=True )
  File "/home/groups/clinical/Galaxy/galaxy-dist/lib/galaxy/tools/__init__.py", line 1921, in check_and_update_param_values
    self.check_and_update_param_values_helper( self.inputs, values, trans, messages, update_values=update_values, allow_workflow_parameters=allow_workflow_parameters )
  File "/home/groups/clinical/Galaxy/galaxy-dist/lib/galaxy/tools/__init__.py", line 1950, in check_and_update_param_values_helper
    values[ input.name ] = input.get_initial_value( trans, context )
  File "/home/groups/clinical/Galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 1880, in get_initial_value
    return self.get_initial_value_from_history_prevent_repeats(trans, context, None, history=history)
  File "/home/groups/clinical/Galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 1890, in get_initial_value_from_history_prevent_repeats
    history = self._get_history( trans, history )
  File "/home/groups/clinical/Galaxy/galaxy-dist/lib/galaxy/tools/parameters/basic.py", line 1660, in _get_history
    assert history is not None, "%s requires a history" % class_name
AssertionError: DataToolParameter requires a history
```

**Comment by nsoranzo** [comment]
@jhl667 Thanks for the bug report! We need some more information to debug your error, e.g.: BioBlend version, Galaxy version and the values of `datamap` and `param_set`.

**Comment by jhl667** [comment]
BioBlend: 0.6.1
Galaxy: 15.03
datamap = {u'1645': {'src': 'ldda', 'id': u'a02953dd78f5f77c'}, u'1647': {'src': 'ldda', 'id': u'6b05e1e55c2bd5bc'}, u'1646': {'src': 'ldda', 'id': u'6f66f7d827200878'}, u'1649': {'src': 'ldda', 'id': u'ffbdff0ba70ee000'}, u'1648': {'src': 'ldda', 'id': u'b6e7362ac4147805'}, u'1652': {'src': 'ldda', 'id': u'0d906eaa636d0cde'}, u'1653': {'src': 'ldda', 'id': u'04050dc48d7ba20a'}, u'1650': {'src': 'ldda', 'id': u'2eaea94e6bd25f54'}, u'1651': {'src': 'ldda', 'id': u'3afb927af0862c9e'}, u'1656': {'src': 'ldda', 'id': u'74a90333cb004907'}, u'1654': {'src': 'ldda', 'id': u'16f71d5b4c6bc471'}, u'1655': {'src': 'ldda', 'id': u'4fee3676e32fb0e8'}}
param_set = {'1489': {'params|readGroup|rgpu': 'AACGTGAT', 'params|readGroup|rgsm': '@NS500390:27:HGYN3BGXX:1', 'params|readGroup|rgid': '@NS500390:27:HGYN3BGXX:1', 'params|readGroup|rglb': '@NS500390:27:HGYN3BGXX:1', 'params|readGroup|rgds': 'Automated variant calling workflow.'}}

**Comment by jhl667** [comment]
This seems to have gone away after updating to newer versions of both BioBlend and Galaxy.
