### ISSUE TITLE
Error when deleting library

### ISSUE THREAD

**Issue by erasche** [galaxyproject/bioblend#164]
Looks like a missing header somewhere.

MWE:

``` python
from bioblend.galaxy import objects
gi = objects.GalaxyInstance(url='', api_key='')

mylib = gi.libraries.create("test")
print mylib
print gi.libraries.delete(mylib.id)
```

Console:

```
Library({u'can_user_add': True, u'description': u'', u'deleted': False, u'can_user_manage': True, u'can_user_modify': True, u'create_time_pretty': u'', u'public': True, u'synopsis': u'', u'create_time': u'2015-10-14T16:40:42.853078', u'root_folder_id': u'Ff812feaac0431f61', u'model_class': u'Library', u'id': u'932767c4db094661', u'name': u'test'})
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    print gi.libraries.delete(mylib.id)
  File "/usr/local/lib/python2.7/dist-packages/bioblend/galaxy/objects/client.py", line 160, in delete
    res = self.gi.libraries.delete_library(id_)
  File "/usr/local/lib/python2.7/dist-packages/bioblend/galaxy/libraries/__init__.py", line 55, in delete_library
    return Client._delete(self, payload, id=library_id)
  File "/usr/local/lib/python2.7/dist-packages/bioblend/galaxy/client.py", line 202, in _delete
    "Unexpected HTTP status code: %s" % r.status_code, body=r.text
bioblend.galaxy.client.ConnectionError: Unexpected HTTP status code: 500: 
```

Server side:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/config.py", line 291, in __call__
    return self.app(environ, start_response)
  File "/home/galaxy/galaxy/lib/galaxy/web/framework/middleware/request_id.py", line 14, in __call__
    return self.app( environ, start_response )
  File "/home/galaxy/galaxy/lib/galaxy/web/framework/middleware/xforwardedhost.py", line 22, in __call__
    return self.app( environ, start_response )
  File "/home/galaxy/galaxy/lib/galaxy/web/framework/middleware/translogger.py", line 70, in __call__
    return self.application(environ, replacement_start_response)
  File "/home/galaxy/galaxy/lib/galaxy/web/framework/middleware/error.py", line 163, in __call__
    response = self.exception_handler(exc_info, environ)
  File "/home/galaxy/galaxy/lib/galaxy/web/framework/middleware/error.py", line 178, in exception_handler
    get_vars = wsgilib.parse_querystring(environ)
  File "/usr/local/lib/python2.7/dist-packages/paste/request.py", line 100, in parse_querystring
    strict_parsing=False)
  File "/usr/lib/python2.7/cgi.py", line 190, in parse_qsl
    PendingDeprecationWarning, 2)
  File "/home/galaxy/galaxy/lib/galaxy/web/framework/middleware/error.py", line 151, in __call__
    app_iter = self.application(environ, sr_checker)
  File "/usr/local/lib/python2.7/dist-packages/paste/recursive.py", line 84, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/paste/httpexceptions.py", line 633, in __call__
    return self.application(environ, start_response)
  File "/home/galaxy/galaxy/lib/galaxy/web/framework/base.py", line 133, in __call__
    return self.handle_request( environ, start_response )
  File "/home/galaxy/galaxy/lib/galaxy/web/framework/base.py", line 191, in handle_request
    body = method( trans, **kwargs )
  File "/home/galaxy/galaxy/lib/galaxy/web/framework/decorators.py", line 230, in decorator
    kwargs['payload'] = __extract_payload_from_request(trans, func, kwargs)
  File "/home/galaxy/galaxy/lib/galaxy/web/framework/decorators.py", line 155, in __extract_payload_from_request
    content_type = trans.request.headers['content-type']
  File "/home/galaxy/galaxy/eggs/WebOb-0.8.5-py2.7.egg/webob/datastruct.py", line 40, in __getitem__
KeyError: 'CONTENT_TYPE'
```

**Comment by nsoranzo** [comment]
I cannot reproduce, and deleting a library in TravisCI tests works on all supported Python and Galaxy versions. Can you dig a bit more?

**Comment by erasche** [comment]
@nsoranzo sorry, missed your reply. I'm seeing this on deleting histories too:

```

**Comment by erasche** [comment]
After pushing everything through mitmproxy...

![mitmproxy](https://cloud.githubusercontent.com/assets/458683/10712831/ecbc42ca-7a6a-11e5-87a9-8c1c723e3679.png)

content-type is definitely not being sent. I believe the root of the problem lies in the differences between the `make_*_request()` methods. Only `make_post_request` makes use of the `self.json_headers` object.

This is on bioblend 0.6.1

**Comment by erasche** [comment]
This is a duplicate of https://github.com/galaxyproject/bioblend/issues/213 which was solved.
