### ISSUE TITLE
Unable to run/invoke workflow when using dataset collection from history

### ISSUE THREAD

**Issue by rat-codes** [galaxyproject/bioblend#228]
Hi all,

I am unable to run a workflow through bioblend. I can execute the same workflow successfully through UI. 

The steps I followed are

1. Create new history
2. Upload 4 fastq files (2 paired-end samples)
3. Create a 'list:paired' collection with above
4. Map the collection['id'] to either step_index (for _'run_workflow'_) or step_order (for _'invoke_workflow'_)

While 'invoke_workflow'  calls does not return any error, 'run_workflow' throws the below error. Both creates a new history as per the _history_name_ param in their calls, but no sign of workflow execution and remains empty. 
```
invocation_wrun_workflow = wfc.run_workflow(workflow['id'], {input_id:{"src":"hda", "id":collection_response["id"]}}, history_name="run_workflow_call", import_inputs_to_history=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/bioblend/galaxy/workflows/__init__.py", line 271, in run_workflow
    return Client._post(self, payload)
  File "/usr/local/lib/python2.7/dist-packages/bioblend/galaxy/client.py", line 157, in _post
    files_attached=files_attached)
  File "/usr/local/lib/python2.7/dist-packages/bioblend/galaxyclient.py", line 134, in make_post_request
    body=r.text, status_code=r.status_code)
bioblend.ConnectionError: Unexpected HTTP status code: 500: {"err_msg": "Uncaught exception in exposed API method:", "err_code": 0}
```

code snippet:
```
gi= GalaxyInstance(url=url, key=key)
hc= HistoryClient(gi)
tc= ToolClient(gi)
wfc= WorkflowClient(gi)

#files 
path="/home/sphadmin/data/fastq_files"
files = {i:os.path.join(path,i) for i in os.listdir(path) if os.path.splitext(i)[1] == '.fastq'}
fwd = re.compile(r'R1')
paired_list = {}
for i in files:
	if fwd.search(i):
		prefix, file = i.split('_R1')[0] , i
		if not prefix in paired_list:
			paired_list[prefix] = {}
		paired_list[prefix]['forward'] = file
	else:
		prefix, file = i.split('_R2')[0], i
		if not prefix  in paired_list:
			paired_list[prefix] = {}
		paired_list[prefix]['reverse'] = file

#history 
history = hc.create_history('Test history')
hda = {i:tc.upload_file(files[i], history['id'], type='fastq',dbkey='H37Rv') for i in files}
files_dataset_id = {i:hda[i]['outputs'][0]['id'] for i in files}
paired_collection = [collections.CollectionElement(name=i,type='paired',elements=[collections.HistoryDatasetElement(name=j,id=files_dataset_id[paired_list[i][j]]) for j in paired_list[i] ]) for i in paired_list]
collectionDesc = collections.CollectionDescription(name='My collection list', type='list:paired', elements=paired_collection)
dataset_collection = hc.create_dataset_collection(history_id=history['id'], collection_description=collectionDesc)

#workflow 
workflow  = [i for i in wfc.get_workflows() if i['name'] == "bwa_2_bcftools_wrename"]
workflow_details = wfc.show_workflow(workflow[0]['id'])
workflow_input_id = workflow_details['inputs'].keys()[0]
run_workflow_datamap = {workflow_input_id : {"src":"hda", "id":dataset_collection['id']} }
invoke_workflow_inputs = {"0": {'id': dataset_collection['id'], 'src':'hda'}}
invoke_wf = wfc.invoke_workflow(workflow[0]['id'], inputs=invoke_workflow_inputs,history_name="Testing workflow")
run_workflow = wfc.run_workflow(workflow[0]['id'], run_workflow_datamap, history_name="Testing workflow thru 'run_workflow'")
```
Appreciate your help!

Thanks,
Aarthi

**Comment by rat-codes** [comment]
My mistake for overlooking the details. Changing the value for "src" as "hdca" resolved the issue. 
`run_workflow_datamap = {workflow_input_id : {"src":"hdca", "id":dataset_collection['id']} }`

Closing this!

**Comment by nsoranzo** [comment]
Good to hear and sorry for not responding before you figured out by yourself.
