### ISSUE TITLE
Issue downloading datasets

### ISSUE THREAD

**Issue by erasche** [galaxyproject/bioblend#253]
cc @bgruening from GIEs I'm seeing the inability to download datasets because of the following line.

https://github.com/galaxyproject/bioblend/blob/f946b3ab5ef7362f0af34d0324b6087eb3d29d5f/bioblend/galaxy/datasets/__init__.py#L108

the requests are made unauthenticated and fail. Adding the API key to the request fixes it. It presents as the following exception:

https://sentry.denbi.uni-freiburg.de/share/issue/322e36323432/

**Comment by erasche** [comment]
```
[22/Sep/2017:11:17:16 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=tabular HTTP/1.1" 500 - "-" "python-requests/2.13.0"
[22/Sep/2017:11:17:38 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=tabular HTTP/1.1" 500 - "-" "python-requests/2.13.0"
[22/Sep/2017:11:17:50 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=tabular HTTP/1.1" 500 - "-" "python-requests/2.13.0"
[22/Sep/2017:11:18:28 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=tabular HTTP/1.1" 500 - "-" "python-requests/2.13.0"
[22/Sep/2017:11:19:15 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=tabular HTTP/1.1" 500 - "-" "python-requests/2.13.0"
[22/Sep/2017:11:21:00 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=tabular HTTP/1.1" 500 - "-" "python-requests/2.13.0"
[10/Oct/2017:21:58:15 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=csv HTTP/1.1" 500 - "-" "python-requests/2.13.0"
[10/Oct/2017:21:59:13 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=csv HTTP/1.1" 500 - "-" "python-requests/2.13.0"
[18/Oct/2017:15:57:10 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=tabular HTTP/1.1" 500 - "-" "python-requests/2.13.0"
[18/Oct/2017:23:32:36 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=csv HTTP/1.1" 500 - "-" "python-requests/2.13.0"
[02/Nov/2017:18:21:21 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=imzml HTTP/1.1" 500 - "-" "python-requests/2.18.1"
[02/Nov/2017:18:21:48 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=imzml HTTP/1.1" 500 - "-" "python-requests/2.18.1"
[06/Nov/2017:15:27:46 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=pdf HTTP/1.1" 500 - "-" "python-requests/2.18.1"
[06/Nov/2017:15:28:20 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=rdata HTTP/1.1" 500 - "-" "python-requests/2.18.1"
[07/Nov/2017:14:30:04 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=rdata HTTP/1.1" 500 - "-" "python-requests/2.18.1"
[07/Nov/2017:17:26:42 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=rdata HTTP/1.1" 500 - "-" "python-requests/2.18.1"
[07/Nov/2017:17:26:50 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=analyze75 HTTP/1.1" 500 - "-" "python-requests/2.18.
[07/Nov/2017:17:27:05 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=rdata HTTP/1.1" 500 - "-" "python-requests/2.18.1"
[07/Nov/2017:17:27:40 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=rdata HTTP/1.1" 500 - "-" "python-requests/2.13.0"
[07/Nov/2017:17:28:11 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=rdata HTTP/1.1" 500 - "-" "python-requests/2.13.0"
[07/Nov/2017:17:29:51 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=analyze75 HTTP/1.1" 500 - "-" "python-requests/2.18.
[07/Nov/2017:22:42:13 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=rdata HTTP/1.1" 500 - "-" "python-requests/2.18.1"
[07/Nov/2017:22:43:26 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=csv HTTP/1.1" 500 - "-" "python-requests/2.18.1"
[08/Nov/2017:19:48:24 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=pdf HTTP/1.1" 500 - "-" "python-requests/2.18.1"
[08/Nov/2017:19:48:44 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=rdata HTTP/1.1" 500 - "-" "python-requests/2.18.1"
[08/Nov/2017:19:48:54 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=analyze75 HTTP/1.1" 500 - "-" "python-requests/2.18.
[08/Nov/2017:19:50:35 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=rdata HTTP/1.1" 500 - "-" "python-requests/2.18.1"
[08/Nov/2017:19:50:47 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=analyze75 HTTP/1.1" 500 - "-" "python-requests/2.18.
[08/Nov/2017:19:50:55 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=csv HTTP/1.1" 500 - "-" "python-requests/2.18.1"
[08/Nov/2017:21:43:59 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=bed HTTP/1.1" 500 - "-" "python-requests/2.18.1"
[10/Nov/2017:17:29:50 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=txt HTTP/1.1" 500 - "-" "python-requests/2.13.0"
[20/Nov/2017:14:03:28 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=json HTTP/1.1" 500 - "-" "python-requests/2.18.1"
[20/Nov/2017:14:04:04 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=json HTTP/1.1" 500 - "-" "python-requests/2.18.1"
[20/Nov/2017:14:05:06 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=json HTTP/1.1" 500 - "-" "python-requests/2.18.1"
[20/Nov/2017:14:05:35 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=json HTTP/1.1" 500 - "-" "python-requests/2.11.1"
[20/Nov/2017:14:05:46 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=json HTTP/1.1" 500 - "-" "python-requests/2.11.1"
[20/Nov/2017:14:07:58 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=tabular HTTP/1.1" 500 - "-" "python-requests/2.11.1"
[20/Nov/2017:14:08:21 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=tabular HTTP/1.1" 500 - "-" "python-requests/2.11.1"
[20/Nov/2017:14:09:26 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=tabular HTTP/1.1" 500 - "-" "python-requests/2.11.1"
[20/Nov/2017:14:10:07 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=tabular HTTP/1.1" 500 - "-" "python-requests/2.11.1"
[20/Nov/2017:14:10:27 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=tabular HTTP/1.1" 500 - "-" "python-requests/2.11.1"
[20/Nov/2017:14:10:52 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=tabular HTTP/1.1" 500 - "-" "python-requests/2.11.1"
[20/Nov/2017:14:11:20 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=tabular HTTP/1.1" 500 - "-" "python-requests/2.11.1"
[20/Nov/2017:14:15:24 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=tabular HTTP/1.1" 500 - "-" "python-requests/2.11.1"
[20/Nov/2017:14:16:47 +0200] "GET /api/histories/<redacted>/contents/<redacted>/display?to_ext=tabular HTTP/1.1" 500 - "-" "python-requests/2.11.1"
```

**Comment by erasche** [comment]
Note that not everyone is seeing this issue. other users seem to have no problem getting datasets.

**Comment by erasche** [comment]
I'm seeing this again with @mtekman on usegalaxy.eu.

``
(.venv) [hxr@mk:~/arbeit/parsec]1$ parsec -g mtekman histories download_dataset adc31fd57dc3c9e2 3d8c403658fba643 asdf
Traceback (most recent call last):
  File "/home/hxr/arbeit/parsec/parsec/decorators.py", line 13, in custom_exception
    return wrapped(*args, **kwargs)
  File "/home/hxr/arbeit/parsec/parsec/decorators.py", line 37, in dict_output
    output = wrapped(*args, **kwargs)
  File "/home/hxr/arbeit/parsec/parsec/commands/histories/download_dataset.py", line 27, in cli
    return ctx.gi.histories.download_dataset(history_id, dataset_id, file_path, use_default_filename=use_default_filename)
  File "/home/hxr/arbeit/parsec/.venv/lib/python3.5/site-packages/bioblend/galaxy/histories/__init__.py", line 429, in download_dataset
    use_default_filename=False)
  File "/home/hxr/arbeit/parsec/.venv/lib/python3.5/site-packages/bioblend/galaxy/datasets/__init__.py", line 109, in download_dataset
    r.raise_for_status()
  File "/home/hxr/arbeit/parsec/.venv/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://usegalaxy.eu/api/histories/b4addb16fa9ed56b/contents/3d8c403658fba643/display?to_ext=txt
500 Server Error: Internal Server Error for url: https://usegalaxy.eu/api/histories/b4addb16fa9ed56b/contents/3d8c403658fba643/display?to_ext=txt
```

Note the missing api key in the URL, and here is the relevant event in our sentry: https://sentry.denbi.uni-freiburg.de/share/issue/322e35323535/
