### ISSUE TITLE
Connection aborted using download_dataset

### ISSUE THREAD

**Issue by clayfos** [galaxyproject/bioblend#269]
Greetings,

I am attempting to download datasets from a history using download_dataset with a local instance of Galaxy.  This same script used to work perfectly, but now I receive the following error seemingly randomly: 

bioblend.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)), 0 attempts left:

What I mean by randomly is that the dataset that throws the error appears to change, sometimes it doesn't happen at all, sometimes it happens when downloading the very first dataset.

**Comment by nsoranzo** [comment]
Ah, [Heisenbugs](https://en.wikipedia.org/wiki/Heisenbug) are the best :cry: 

Are you using [gi.datasets.download_dataset()](https://bioblend.readthedocs.io/en/latest/api_docs/galaxy/all.html#bioblend.galaxy.datasets.DatasetClient.download_dataset) or the deprecated [gi.histories.download_dataset()](https://bioblend.readthedocs.io/en/latest/api_docs/galaxy/all.html#bioblend.galaxy.histories.HistoryClient.download_dataset) ? I think with the former you shouldn't encounter that error.

**Comment by clayfos** [comment]
Ha yes, they are certainly frustrating.

I've been using the current gi.datasets.dowload_dataset(), specifically:
    gi.datasets.download_dataset(d['id'], file_path=new_filepath, use_default_filename=False)

When the error occurs, I seem to be able to access the full_details of the job that created each dataset using show_job(), along with other information about the dataset.  It just doesn't like when I then attempt to download it.  My current inefficient workaround is just using delete_dataset() to purge datasets after they download, making it easy to try again on the unsuccessful ones.

**Comment by nsoranzo** [comment]
Then I think that the pattern is: `gi.datasets.download_dataset()` calls `self._block_until_dataset_terminal(dataset_id, maxwait=maxwait)` as first thing, which in turn calls `self.show_dataset(dataset_id)` in a loop until the dataset state is terminal. Each `show_dataset()` in turn calls `Client._get()`, which tries twice the GET request before erroring with the reported `bioblend.ConnectionError` exception.

One thing you can try is increase the number of retries for the GET requests by executing `gi.datasets.set_max_get_retries(N)` once at the start of your script.

**Comment by clayfos** [comment]
I gave that a shot but still getting random disconnects.  Here's the full output after increasing max_get_retries:

`Traceback (most recent call last):
  File "/home/cfo/miniconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/cfo/miniconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/cfo/miniconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/home/cfo/miniconda3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/home/cfo/miniconda3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/home/cfo/miniconda3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cfo/miniconda3/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/cfo/miniconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/cfo/miniconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/cfo/miniconda3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/cfo/miniconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/cfo/miniconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/cfo/miniconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/home/cfo/miniconda3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/home/cfo/miniconda3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/home/cfo/miniconda3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bioblend_script_download_entire_history_with_parameters_and_stdouts_new2.py", line 67, in <module>
    gi.datasets.download_dataset(d['id'], file_path=new_filepath, use_default_filename=False)
  File "/home/cfo/miniconda3/lib/python3.6/site-packages/bioblend/galaxy/datasets/__init__.py", line 108, in download_dataset
    r = self.gi.make_get_request(url, stream=stream_content)
  File "/home/cfo/miniconda3/lib/python3.6/site-packages/bioblend/galaxyclient.py", line 99, in make_get_request
    r = requests.get(url, **kwargs)
  File "/home/cfo/miniconda3/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/cfo/miniconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/cfo/miniconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/cfo/miniconda3/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/cfo/miniconda3/lib/python3.6/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))`
