### ISSUE TITLE
Workflow with collection fails to execute but works through UI

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/bioblend#276]
I have a workflow that uses dataset collections, which works through the interface, but produces an error when running through bioblend (latest installable pip version):

```
Traceback (most recent call last):
  File "lib/galaxy/tools/__init__.py", line 1416, in handle_single_execution
    completed_job=completed_job,
  File "lib/galaxy/tools/__init__.py", line 1497, in execute
    return self.tool_action.execute(self, trans, incoming=incoming, set_output_hid=set_output_hid, history=history, **kwargs)
  File "lib/galaxy/tools/actions/__init__.py", line 455, in execute
    **element_kwds
  File "lib/galaxy/tools/actions/__init__.py", line 867, in create_collection
    **element_kwds
  File "lib/galaxy/managers/collections.py", line 119, in create
    trans, parent, name, dataset_collection, implicit_inputs=implicit_inputs, implicit_output_name=implicit_output_name, tags=tags
  File "lib/galaxy/managers/collections.py", line 137, in _create_instance_for_collection
    parent.add_dataset_collection(dataset_collection_instance)
  File "lib/galaxy/model/__init__.py", line 1425, in add_dataset_collection
    history_dataset_collection.hid = self._next_hid()
  File "lib/galaxy/model/mapping.py", line 2544, in db_next_hid
    table.update(table.c.id == self.id).execute(hid_counter=(next_hid + n))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
galaxy.tools.execute WARNING 2019-02-26 17:22:43,532 [p:180,w:2,m:0] [uWSGIWorker2Core0] There was a failure executing a job for tool [_scanpy_parameter_iterator] - Error executing tool: unsupported operand type(s) for +: 'NoneType' and 'int'
```

On current version of Galaxy, this can be traced here:

https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/model/mapping.py#L2571

I'm surprised though that the execution is falling into a conditional where postgres is not in session.bind.dialect.name, given that we are running on postgres. We don't see this issue when running the workflow with the same data manually through the UI. Any ideas? The setup is running on 18.05 still.

**Comment by nsoranzo** [comment]
That looks like a Galaxy issue to me, BioBlend is just a thin layer over the Galaxy API.
