### ISSUE TITLE
JSONDecodeError for executing show_workflow()

### ISSUE THREAD

**Issue by lee212** [galaxyproject/bioblend#31]
Hi,

I tried to call `show_workflow()` but I got errors like this:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/bioblend/galaxy/workflows/__init__.py", line 45, in show_workflow
    return Client._get(self, id=workflow_id)
  File "/usr/local/lib/python2.7/dist-packages/bioblend/galaxy/client.py", line 35, in _get
    return r.json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 651, in json
    return json.loads(self.text or self.content, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 413, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 402, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 420, in raw_decode
    raise JSONDecodeError("No JSON object could be decoded", s, idx)
simplejson.decoder.JSONDecodeError: No JSON object could be decoded: line 1 column 0 (char 0)
```

The code snippets that I tried look like this:

```
from bioblend.galaxy import GalaxyInstance

galaxy_url = "http://127.0.0.1:8080"
galaxy_api_key = "d8688f27a08cc6f42a065e39966b6c47"
gi = GalaxyInstance(url=galaxy_url, key=galaxy_api_key)
workflows = gi.workflows.get_workflows()[0]
gi.workflows.show_workflow(workflows['id'])
```

So, I printed the workflows variable to make sure it has an id.

```
print workflows
{u'name': u"Workflow 1", u'tags': [], u'url': u'/api/workflows/f597429621d6eb2b', u'published': True, u'model_class': u'StoredWorkflow', u'id': u'f597429621d6eb2b'}
```

Is there something that I missed?

Thanks,
Hyungro

**Comment by nsoranzo** [comment]
I cannot replicate when running `gi.workflows.show_workflow('b62535ba597d3323')`, feel free to reopen if it is still an issue.
