### ISSUE TITLE
Unexpected HTTP status code: 500

### ISSUE THREAD

**Issue by Colorstorm** [galaxyproject/bioblend#315]
Hi, 
I am try to export a galaxy history in python.
From some histories I get `bioblend.ConnectionError: Unexpected HTTP status code: 500:`
What does these error mean and is it possible to avoid the error?

Here is my code:
```
from bioblend.galaxy import GalaxyInstance

ip = '***.***.***.***'
api_key = '*************************'
history_id = '***************'
gi = GalaxyInstance(url=ip, key=api_key)
histories_list = gi.histories.get_histories(deleted=False)
jeha_id = gi.histories.export_history(history_id, gzip=True, include_hidden=False,   include_deleted=False, wait=True, maxwait=None)
f = open("test/" + history_id + '.tar.gz', 'wb')
gi.histories.download_history(history_id=history['id'], jeha_id=jeha_id, outf=f)
f.close()
```

Here is the full error message:
```
Traceback (most recent call last):
  File "/Path/to/python/file/exportTest.py", line 8, in <module>
    jeha_id = gi.histories.export_history(history_id, gzip=True, include_hidden=False, include_deleted=False, wait=True, maxwait=None)
  File "/Path/to/python/interpreter/venv/lib/python3.5/site-packages/bioblend/galaxy/histories/__init__.py", line 617, in export_history
    r = self._put(payload={}, url=url, params=params)
  File "/Path/to/python/interpreter/venv/lib/python3.5/site-packages/bioblend/galaxy/client.py", line 165, in _put
    return self.gi.make_put_request(url, payload=payload, params=params)
  File "/Path/to/python/interpreter/venv/lib/python3.5/site-packages/bioblend/galaxyclient.py", line 214, in make_put_request
    body=r.text, status_code=r.status_code)
bioblend.ConnectionError: Unexpected HTTP status code: 500: {"err_msg": "Uncaught exception in exposed API method:", "err_code": 0}
```

**Comment by nsoranzo** [comment]
Any chance you can check the Galaxy logs of your server when this error happens?

**Comment by Colorstorm** [comment]
Is this what you are looking for?
```
TypeError: <galaxy.model.HistoryDatasetCollectionAssociation object at 0x7fcda16ee390> is not JSON serializable
172.24.2.46 - - [22/Jan/2020:14:34:26 +0200] "PUT /api/histories/********************/exports?gzip=True&include_hidden=False&key=************************************&include_deleted=False HTTP/1.1" 500 - "-" "pyt
[pid: 1546|app: 0|req: 811/1622] 172.24.2.46 () {44 vars in 823 bytes} [Wed Jan 22 14:34:26 2020] PUT /api/histories/79966582feb6c081/exports?gzip=True&include_hidden=False&key=*******************************
172.24.2.46 - - [22/Jan/2020:15:54:53 +0200] "GET /api/histories?key=************************** HTTP/1.1" 200 - "-" "python-requests/2.22.0"
[pid: 1547|app: 0|req: 812/1623] 172.24.2.46 () {40 vars in 589 bytes} [Wed Jan 22 15:54:53 2020] GET /api/histories?key=f968d68093d67f447536a7be5c17b688 => generated 7489 bytes in 98 msecs (HTTP/1.1 200)
galaxy.web.framework.decorators ERROR 2020-01-22 15:54:54,259 [p:1547,w:2,m:0] [uWSGIWorker2Core0] Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 281, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/histories.py", line 473, in archive_export
    self.queue_history_export(trans, history, gzip=gzip, include_hidden=include_hidden, include_deleted=include_deleted)
  File "lib/galaxy/web/base/controller.py", line 418, in queue_history_export
    history_exp_tool.execute(trans, incoming=params, history=history, set_output_hid=True)
  File "lib/galaxy/tools/__init__.py", line 1497, in execute
    return self.tool_action.execute(self, trans, incoming=incoming, set_output_hid=set_output_hid, history=history, **kwargs)
  File "lib/galaxy/tools/actions/history_imp_exp.py", line 124, in execute
    include_deleted=incoming['include_deleted'])
  File "lib/galaxy/tools/imp_exp/__init__.py", line 495, in setup_job
    jobs_attrs_out.write(dumps(jobs_attrs, cls=HistoryDatasetAssociationEncoder))
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "lib/galaxy/tools/imp_exp/__init__.py", line 374, in default
    return json.JSONEncoder.default(self, obj)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <galaxy.model.HistoryDatasetCollectionAssociation object at 0x7fcdcdf22f10> is not JSON serializable
172.24.2.46 - - [22/Jan/2020:15:54:53 +0200] "PUT /api/histories/**********************/exports?gzip=True&key=*******************************************&include_deleted=False&include_hidden=False HTTP/1.1" 500 - "-" "pyt
[pid: 1547|app: 0|req: 813/1624] 172.24.2.46 () {44 vars in 823 bytes} [Wed Jan 22 15:54:53 2020] PUT /api/histories/************************/exports?gzip=True&key=**********************************&include_deleted
```
