### ISSUE TITLE
Unknown step type: 'parameter_input'

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/bioblend#316]
```
Traceback (most recent call last):
...
    workflows = conn.workflows.list(name=workflow_name, published=True)  # There should only be one
  File "/home/nolan/Projects/islandcompare-cli/venv/lib/python3.8/site-packages/bioblend/galaxy/objects/client.py", line 308, in list
    return [self.get(_['id']) for _ in dicts]
  File "/home/nolan/Projects/islandcompare-cli/venv/lib/python3.8/site-packages/bioblend/galaxy/objects/client.py", line 308, in <listcomp>
    return [self.get(_['id']) for _ in dicts]
  File "/home/nolan/Projects/islandcompare-cli/venv/lib/python3.8/site-packages/bioblend/galaxy/objects/client.py", line 288, in get
    return wrappers.Workflow(wf_dict, gi=self.obj_gi)
  File "/home/nolan/Projects/islandcompare-cli/venv/lib/python3.8/site-packages/bioblend/galaxy/objects/wrappers.py", line 211, in __init__
    step = Step(v, self)
  File "/home/nolan/Projects/islandcompare-cli/venv/lib/python3.8/site-packages/bioblend/galaxy/objects/wrappers.py", line 170, in __init__
    raise ValueError('Unknown step type: %r' % stype)
ValueError: Unknown step type: 'parameter_input'
```
It looks like bioblend doesn't support simple workflow inputs or subworkflows.

**Comment by nsoranzo** [comment]
Does this patch fixes the issue for you?

```diff
diff --git a/bioblend/galaxy/objects/wrappers.py b/bioblend/galaxy/objects/wrappers.py
index b5100c0..c6138d8 100644
--- a/bioblend/galaxy/objects/wrappers.py
+++ b/bioblend/galaxy/objects/wrappers.py
@@ -154,8 +154,9 @@ class Step(Wrapper):
     Abstract base class for workflow steps.
 
     Steps are the main building blocks of a Galaxy workflow. A step can be: an
-    input (type 'data_collection_input` or 'data_input`), a computational tool
-    (type 'tool`) or a pause (type 'pause`).
+    input (type ``data_collection_input``, ``data_input`` or
+    ``parameter_input``), a computational tool (type ``tool``), a subworkflow
+    (type ``subworkflow``) or a pause (type ``pause``).
     """
     BASE_ATTRS = Wrapper.BASE_ATTRS + (
         'input_steps', 'tool_id', 'tool_inputs', 'tool_version', 'type'
@@ -167,8 +168,7 @@ class Step(Wrapper):
             stype = step_dict['type']
         except KeyError:
             raise ValueError('not a step dict')
-        if stype not in set(['data_collection_input', 'data_input', 'pause',
-                             'tool']):
+        if stype not in {'data_collection_input', 'data_input', 'parameter_input', 'pause', 'subworkflow', 'tool'}:
             raise ValueError('Unknown step type: %r' % stype)
         if self.type == 'tool' and self.tool_inputs:
             for k, v in self.tool_inputs.items():
```

**Comment by innovate-invent** [comment]
```
Traceback (most recent call last):
 ...
  File "/home/nolan/Projects/islandcompare-cli/islandcompare.py", line 60, in get_workflow
    workflows = conn.workflows.list(name=workflow_name, published=True)  # There should only be one
  File "/home/nolan/Projects/islandcompare-cli/venv/lib/python3.8/site-packages/bioblend/galaxy/objects/client.py", line 308, in list
    return [self.get(_['id']) for _ in dicts]
  File "/home/nolan/Projects/islandcompare-cli/venv/lib/python3.8/site-packages/bioblend/galaxy/objects/client.py", line 308, in <listcomp>
    return [self.get(_['id']) for _ in dicts]
  File "/home/nolan/Projects/islandcompare-cli/venv/lib/python3.8/site-packages/bioblend/galaxy/objects/client.py", line 288, in get
    return wrappers.Workflow(wf_dict, gi=self.obj_gi)
  File "/home/nolan/Projects/islandcompare-cli/venv/lib/python3.8/site-packages/bioblend/galaxy/objects/wrappers.py", line 227, in __init__
    assert set(self.inputs) == self.data_collection_input_ids | self.data_input_ids, \
AssertionError: inputs is {'0': {'uuid': '11b0dc1e-0b25-4aab-802c-ff9fdd6d32ab', 'value': '', 'label': 'Newick Identifiers'}, '1': {'uuid': '7629a68d-f23b-4093-a8b2-536165054df0', 'value': '', 'label': 'Reference Genome'}, '2': {'uuid': '7a81e28b-cab5-4cf8-a581-1044ee0b8516', 'value': '', 'label': 'list:list of data and optional inputs'}}, while data_collection_input_ids is {'2'} and data_input_ids is set()
```

**Comment by nsoranzo** [comment]
I've fixed also the second error on the `master` branch, please let us know if you find more issues.
