### ISSUE TITLE
export history error

### ISSUE THREAD

**Issue by davidchristiany** [galaxyproject/bioblend#329]
I am having an error with the last version of bioblend when I use the 'export_history' method.

When I install bioblend with `pip install bioblend` and use python 3.8.2, it works just fine.
But I need the import_history method added in december 2019.
Since the last release is from august 2019, I installed bioblend this way:
`python3 -m pip install git+https://github.com/galaxyproject/bioblend`

With this version, when I want to get a jeha_id with 'export_history()', the first time, I got the following error:
```
Traceback (most recent call last):
  File "/projet/maiage/save/dchristiany/.conda/envs/galaxy_test/lib/python3.8/site-packages/bioblend/galaxy/histories/__init__.py", line 599, in export_history
    r = self._put(payload={}, url=url, params=params)
  File "/projet/maiage/save/dchristiany/.conda/envs/galaxy_test/lib/python3.8/site-packages/bioblend/galaxy/client.py", line 186, in _put
    return self.gi.make_put_request(url, payload=payload, params=params)
  File "/projet/maiage/save/dchristiany/.conda/envs/galaxy_test/lib/python3.8/site-packages/bioblend/galaxyclient.py", line 186, in make_put_request
    raise ConnectionError("Unexpected HTTP status code: %s" % r.status_code,
bioblend.ConnectionError: Unexpected HTTP status code: 202: ""

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "transfert_galaxy_users.py", line 149, in <module>
    main()
  File "transfert_galaxy_users.py", line 122, in main
    galaxy_ref.download_histories(user,histories_path,args.skip_pending_histories)
  File "/projet/maiage/work/dchristiany/galaxy/galaxy_transfer_scripts/galaxy_scripts/instance.py", line 97, in download_histories
    pending_histories = self.init_history_archives(histories,user.histories)                         #init histories archives
  File "/projet/maiage/work/dchristiany/galaxy/galaxy_transfer_scripts/galaxy_scripts/instance.py", line 88, in init_history_archives
    jeha_id=histories.export_history(id, gzip=True, include_hidden=False, include_deleted=False, wait=False)
  File "/projet/maiage/save/dchristiany/.conda/envs/galaxy_test/lib/python3.8/site-packages/bioblend/galaxy/histories/__init__.py", line 604, in export_history
    if time_left > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

And when I try again with the same command line, it works.

I guess something changed when bioblend ask if the export history is ready to galaxy

**Comment by davidchristiany** [comment]
this issue can be bypassed by setting maxwait in export_history:
`export_history(self, history_id, gzip=True, include_hidden=False,
                       include_deleted=False, wait=False, maxwait=None)`
