### ISSUE TITLE
Uncaught exception in exposed API method when trying to create new history

### ISSUE THREAD

**Issue by Mada2** [galaxyproject/bioblend#335]
Hi, I'm trying to automate the provisioning of some galaxy containers using bioblend, and for that I need to be able to create new histories in which the various datasets belong. However every time I try to create a new history using the bioblend method ```instance.histories.create_history(name=xxxx)```, it causes the following error: 

```bioblend.ConnectionError: Unexpected HTTP status code: 500: {"err_msg": "Uncaught exception in exposed API method:", "err_code": 0}```

Here is the complete error log:
```
Traceback (most recent call last):
  File "/xxx/xxx/xxx/xxx/xxx/xxx/xxx/xxx/autoload.py", line 831, in <module>
    al.init_instance()
  File "/xxx/xxx/xxx/xxx/xxx/xxx/xxx/xxx/autoload.py", line 603, in init_instance
    self.connect_to_instance()
  File "/xxx/xxx/xxx/xxx/xxx/xxx/xxx/xxx/autoload.py", line 149, in connect_to_instance
    self.instance.histories.create_history(name=str(self.full_name))
  File "/xxx/xxx/xxx/xxx/xxx/xxx/xxx/lib/python3.8/site-packages/bioblend/galaxy/histories/__init__.py", line 37, in create_history
    return self._post(payload)
  File "/xxx/xxx/xxx/xxx/xxx/xxx/xxx/lib/python3.8/site-packages/bioblend/galaxy/client.py", line 172, in _post
    return self.gi.make_post_request(url, payload=payload,
  File "/xxx/xxx/xxx/xxx/xxx/xxx/xxx/lib/python3.8/site-packages/bioblend/galaxyclient.py", line 131, in make_post_request
    raise ConnectionError("Unexpected HTTP status code: %s" % r.status_code,
bioblend.ConnectionError: Unexpected HTTP status code: 500: {"err_msg": "Uncaught exception in exposed API method:", "err_code": 0}
```
I'm running bioblend 0.14.0, and it didn't happen when I was using version  0.13.0.

As the error message points to no specific reason for this failure, help would be greatly appreciated in order to determine what is going wrong. I though it might be because I use a environment "master" API key to access the galaxy instance of a galaxy container, but I can connect to it just fine using the url and this API key. 

Thank you in advance :smiley: :

**Comment by mvdbeek** [comment]
I don't think you can use the master API key to create histories, as the master API key has no user, and histories need a user.
Can you look at the galaxy logs and check what the traceback there is ?

**Comment by Mada2** [comment]
Here it is @mvdbeek 
```
xxxx@xxxx    | galaxy.web.framework.webapp INFO 2020-09-02 13:48:28,596 [p:2874,w:2,m:0] [uWSGIWorker2Core0] Session authenticated using Galaxy master api key
xxxx@xxxx     | galaxy.web.framework.decorators ERROR 2020-09-02 13:48:28,616 [p:2874,w:2,m:0] [uWSGIWorker2Core0] Uncaught exception in exposed API method:
xxxx@xxxx     | Traceback (most recent call last):
xxxx@xxxx     |   File "lib/galaxy/web/framework/decorators.py", line 295, in decorator
xxxx@xxxx     |     rval = func(self, trans, *args, **kwargs)
xxxx@xxxx     |   File "lib/galaxy/webapps/galaxy/api/histories.py", line 356, in create
xxxx@xxxx     |     self.manager.set_current(trans, new_history)
xxxx@xxxx     |   File "lib/galaxy/managers/histories.py", line 121, in set_current
xxxx@xxxx     |     trans.set_history(history)
xxxx@xxxx     |   File "lib/galaxy/web/framework/webapp.py", line 790, in set_history
xxxx@xxxx     |     self.galaxy_session.current_history = history
xxxx@xxxx     | AttributeError: 'NoneType' object has no attribute 'current_history'

```
It seems you're right, guess I will have to access the instance with a email/password then

**Comment by mvdbeek** [comment]
It actually looks like the history itself was created, but there's no session yet for that interaction.
I think it's best to use a real user to create histories though, I think userless and sessionless histories are not fitting well into how Galaxy manages items.

**Comment by mvdbeek** [comment]
In either case that makes this a Galaxy issue. We can surely do better than just throwing an internal server error.
