### ISSUE TITLE
Error 500 when trying to show or download datasets of other users with admin API key

### ISSUE THREAD

**Issue by jancrichter** [galaxyproject/bioblend#420]
I am using bioblend 0.16.0 to access Galaxy 21.05.

When I am trying to use *.datasets.show_dataset() or *datasets.download_dataset() on datasets that are not my own I get an error 500.

Is this intended? My expectation would be that I can access them in this fashion, as I can also do so when using the web API in the browser.

**Comment by nsoranzo** [comment]
Error 500 is not a permission problem, it's an internal server error. Can you share your relevant BioBlend code and, if possible, the corresponding Galaxy logs?

**Comment by jancrichter** [comment]
Sorry for forgetting to post logs right away, once again.

This is from galaxy.log:

```
galaxy.web.framework.decorators ERROR 2022-03-12 20:39:29,405 [pN:main.web.1,p:11284,w:1,m:0,tN:uWSGIWorker1Core0] Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 184, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/datasets.py", line 134, in show
    dataset = self.get_hda_or_ldda(trans, hda_ldda=hda_ldda, dataset_id=id)
  File "lib/galaxy/webapps/base/controller.py", line 1069, in get_hda_or_ldda
    return self.get_hda(trans, dataset_id, check_ownership=False, check_accessible=True)
  File "lib/galaxy/webapps/base/controller.py", line 1105, in get_hda
    error("You are not allowed to access this dataset")
  File "lib/galaxy/web/framework/decorators.py", line 32, in error
    raise MessageException(message, type='error')
galaxy.exceptions.MessageException: You are not allowed to access this dataset

```


Here is a minimal code example, trying to access a dataset that is in the history of another user, while using an admin API key.

```
from bioblend import galaxy

gi = galaxy.GalaxyInstance(
    url = url, 
    key = key,
)

gi.datasets.download_dataset("b1b1f94bc6f5d08f")
```

This is the error I get in Jupyter:

```
---------------------------------------------------------------------------
ConnectionError                           Traceback (most recent call last)
<ipython-input-12-0c9786606751> in <module>
      6 )
      7 
----> 8 gi.datasets.download_dataset("b1b1f94bc6f5d08f")

<redacted_path>/bioblend/lib/python3.8/site-packages/bioblend/galaxy/datasets/__init__.py in download_dataset(self, dataset_id, file_path, use_default_filename, require_ok_state, maxwait)
     90                  Otherwise returns nothing.
     91         """
---> 92         dataset = self.wait_for_dataset(dataset_id, maxwait=maxwait, check=False)
     93         if not dataset['state'] == 'ok':
     94             message = f"Dataset state is not 'ok'. Dataset id: {dataset_id}, current state: {dataset['state']}"

<redacted_path>//bioblend/lib/python3.8/site-packages/bioblend/galaxy/datasets/__init__.py in wait_for_dataset(self, dataset_id, maxwait, interval, check)
    382         time_left = maxwait
    383         while True:
--> 384             dataset = self.show_dataset(dataset_id)
    385             state = dataset['state']
    386             if state in TERMINAL_STATES:

<redacted_path>/bioblend/lib/python3.8/site-packages/bioblend/galaxy/datasets/__init__.py in show_dataset(self, dataset_id, deleted, hda_ldda)
     52             hda_ldda=hda_ldda,
     53         )
---> 54         return self._get(id=dataset_id, deleted=deleted, params=params)
     55 
     56     def download_dataset(self, dataset_id, file_path=None, use_default_filename=True,

<redacted_path>/bioblend/lib/python3.8/site-packages/bioblend/galaxy/client.py in _get(self, id, deleted, contents, url, params, json)
    146             if attempts_left <= 0:
    147                 bioblend.log.error(msg)
--> 148                 raise ConnectionError(
    149                     msg,
    150                     body=r.text,

ConnectionError: GET: error 500: b'<html>\r\n  <head><title>Internal Server Error</title></head>\r\n  <body>\r\n    <h1>Internal Server Error</h1>\r\n    <p>The server has either erred or is incapable of performing\r\nthe requested operation.\r\n\r\n<br/>\r\n<!--  --></p>\r\n    <hr noshade>\r\n    <div align="right">WSGI Server</div>\r\n  </body>\r\n</html>\r\n', 0 attempts left: <html>
  <head><title>Internal Server Error</title></head>
  <body>
    <h1>Internal Server Error</h1>
    <p>The server has either erred or is incapable of performing
the requested operation.

<br/>
<!--  --></p>
    <hr noshade>
    <div align="right">WSGI Server</div>
  </body>
</htm
```

**Comment by davelopez** [comment]
I think this issue has been fixed in https://github.com/galaxyproject/galaxy/pull/13060

**Comment by jancrichter** [comment]
If I understand you correctly this means, the problem is on Galaxy side and updating to latest on 21.05 or to 21.09 would solve the issue?

**Comment by davelopez** [comment]
Yes, the problem is on Galaxy side, but you will need to update it to 22.01

**Comment by mvdbeek** [comment]
We should backport the fix though, if it works on older releases

**Comment by jancrichter** [comment]
Alright, thanks for the infos. I think we are going to adopt 22.01 rather early, but a backport would be perfect.

Feel free to close this, unless you want to move it and start a backport off of it or something.
